# Generated by Django 5.2 on 2026-05-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='status',
            field=models.TextField(choices=[('INIT', 'Инициализация забега'), ('IN_PROGRESS', 'Забег в процессе'), ('FINISHED', 'Забег окончен')], default='IN_PROGRESS'),
        ),
    ]
