# Generated by Django 5.2 on 2026-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_athleteinfo_user_id_alter_athleteinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.SmallIntegerField(default=None),
        ),
    ]
