# Generated by Django 5.2 on 2026-05-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0007_alter_athleteinfo_goals_alter_athleteinfo_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
