# Generated by Django 5.2 on 2026-05-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0008_rename_user_id_athleteinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='athleteinfo',
            name='weight',
            field=models.TextField(),
        ),
    ]
