# Generated by Django 5.2 on 2026-05-18 08:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0012_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Challenge',
            new_name='Challenges',
        ),
    ]
