# Generated by Django 5.2 on 2026-05-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_positions'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positions',
            name='longitude',
            field=models.FloatField(default=12),
            preserve_default=False,
        ),
    ]
