# Generated by Django 5.2 on 2026-05-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0015_positions_latitude_positions_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
