# Generated by Django 5.2 on 2026-05-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0019_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='failed',
            field=models.TextField(null=True),
        ),
    ]
