# Generated by Django 5.2 on 2026-05-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0021_alter_uploadfile_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
