# Generated by Django 5.2 on 2026-05-23 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0023_collectibleitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
