# Generated by Django 5.2 on 2026-05-23 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_positions_date_time_run_run_time_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
