# Generated by Django 5.2 on 2026-05-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0024_alter_collectibleitem_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectibleitem',
            name='uid',
        ),
    ]
