# Generated by Django 5.2 on 2026-05-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_remove_collectibleitem_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='uid',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
