# Generated by Django 5.2 on 2026-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0025_alter_positions_date_time_alter_run_run_time_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
