# Generated by Django 5.2 on 2026-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0026_positions_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
