# Generated by Django 5.2 on 2026-05-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0027_positions_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.FloatField(null=True),
        ),
    ]
