# Generated by Django 5.2 on 2026-05-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0028_run_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='speed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
