# Generated by Django 5.2 on 2026-05-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0029_alter_positions_speed_alter_run_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField()),
                ('coach_id', models.IntegerField()),
            ],
        ),
    ]
